repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.5
    hooks:
    - id: ruff
      name: Ruff check
      description: "Run 'ruff check' for extremely fast Python linting"
      args: [ --fix ]
    - id: ruff-format
      name: Ruff format
      description: "Run 'ruff format' for extremely fast Python formatting"
  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint-docker
        name: Lint Dockerfiles
        description: Runs hadolint Docker image to lint Dockerfiles
        language: docker_image
        types: ["dockerfile"]
        entry: ghcr.io/hadolint/hadolint hadolint
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
    - id: bandit
      exclude: ^tests/
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: check-yaml
      types: [yaml]
    - id: check-json
      types: [json]
    - id: check-toml
      types: [toml]
    - id: no-commit-to-branch
      args: ["--branch", "main"]