---
services:
  code-server:
    image: codecentric/from-jupyter-to-production-code-server
    privileged: true
    environment:
      - PUID=0
      - PGID=0
      - TZ=Etc/UTC
      - DEFAULT_WORKSPACE=/workspace
    volumes:
      - ./src:/workspace/src
      - ./pyproject.toml:/workspace/pyproject.toml
      - ./data:/workspace/data
      - .dockerignore:/workspace/.dockerignore
      - ./uv.lock:/workspace/uv.lock
      - ./Dockerfile:/workspace/Dockerfile
      - ./README.md:/workspace/README.md
    stdin_open: true # Keep stdin open for interactive use
    tty: true        # Allocate a pseudo-TTY for the container
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8443/" ]
      interval: 30s
      timeout: 10s
      retries: 3
    ports:
      - "8443:8443"